imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

nelmio_api_doc: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

killerwolf_jc_decaux_cyclocity:
    api_key: "f45498cb16945d7148441dd9be88a9ee7ede91de"

fos_rest:
    format_listener:
        rules:
            - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format: json
        include_format: false

guzzle:
    clients:
        api_bordeaux:
            base_url: http://data.bordeaux-metropole.fr/wfs
        api_nice:
            base_url: https://www.velobleu.org/cartoV2/libProxyCarto.asp